# branches: main

pipeline:
  code_lint:
    image: pipelinecomponents/luacheck
    commands:
      - luacheck lua/zettelkasten

  unit_tests:
    image: imega/busted
    commands:
      - busted test -C lua

  notify_matrix:
    image: plugins/matrix
    settings:
      homeserver: https://matrix.org
      roomid:
        from_secret: matrix_roomid
      userid:
        from_secret: matrix_userid
      accesstoken:
        from_secret: matrix_token
    when:
      status: [ success, failure ]

